services:
  - type: web
    name: potato-backend
    env: python
    buildCommand: |
      echo "python-3.8.13" > .render/python-version
      pip install -r Potato-disease-predictor/api/requirements.txt
    startCommand: uvicorn main:app --host=0.0.0.0 --port=10000
    runtime: python
    branch: main
    plan: free
    region: oregon
    rootDir: Potato-disease-predictor/api

  - type: web
    name: potato-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    branch: main
    plan: free
    region: oregon
    rootDir: potato-disease-frontend1
